// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef configform_h
#define configform_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Check_Button.H>
#include <FL/Fl_Button.H>
extern void configOkayButton_cb(Fl_Button*, void*);

class ConfigUI : public Fl_Double_Window {
  void _ConfigUI();
public:
  ConfigUI(int X, int Y, int W, int H, const char *L = 0);
  ConfigUI(int W, int H, const char *L = 0);
  ConfigUI();
  Fl_Tabs *configTabs;
  Fl_Group *editorGroup;
  Fl_Check_Button *singleBufferToggle;
  Fl_Check_Button *shadersToggle;
  Fl_Check_Button *systemColorsToggle;
  Fl_Check_Button *easterEggToggle;
private:
  inline void cb_Cancel_i(Fl_Button*, void*);
  static void cb_Cancel(Fl_Button*, void*);
};
#endif
