name: Build and release

on:
  push:
    branches: [ linux-build ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install build-essential libtinyxml2-6 libtinyxml2-dev libfltk1.3-dev libglew-dev xorg-dev
    - name: make
      run: make -f Makefile CONF=Debug-linux
    - name: Create archive
      run: 7z a smxtool-0.18b-linux.zip ${{github.workspace}}/dist/Debug-linux/GNU-Linux
    - name: Upload sxmtool-linux
      uses: actions/upload-artifact@v2
      with: 
        name: smxtool-0.18b-linux.zip
        path: ${{github.workspace}}/dist/Debug-linux/GNU-Linux
    - name: Create a Release
      uses: djnicholson/release-action@v2.11
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        release-name: 'Latest Linux build'
        tag-name: 'v0.18b'
        asset-name: 'smxtool-0.18b-linux.zip'
        file: 'smxtool-0.18b-linux.zip'
